### PR TITLE
Implement plugin data accessors

### PR DESCRIPTION
**Pull request by bpjordan**
Implements accessors for plugin metadata that can be passed through the API

Adds `PluginMetadata` struct which serializes into the JSON object found in `docs/api.md`.

Implements `PluginManager::list_metadata()` which returns a hash map of `PluginMetadata` objects with UUIDs as keys (which in turn serializes to the JSON dictionary found in `docs/api.md` under the `/api/plugins` endpoint).

Implements `PluginManager::get_metadata(uuid)` which returns the `PluginMetadata` object referring to the plugin with the given UUID

### CODE REVIEW

**Review by carterray31001 — DISMISSED** [review]
I'm sure this works

**Review by tchuhn — APPROVED** [review]
Everything looks great 👍

**Comment by SethajWarren** [comment]
yes

**Review by SethajWarren — APPROVED** [review]
I like this

**Review by carterray31001 — APPROVED** [review]

**Review by tchuhn — APPROVED** [review]

**Pull request merged**
